### ISSUE TITLE
Incompatible with Sphinx 3.0

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/sphinx-hoverxref#45]
Sphinx 3.0 was released two hours ago, and [we noticed in our pipelines](https://dev.azure.com/poliastro/poliastro/_build/results?buildId=124&view=logs&j=f7cd7807-82c0-5095-6e59-d04f697ea1d8&t=6b55555c-5bc2-5302-9933-bfad45886ef1&l=75) this error coming from sphinx-hoverxref:

```python

Traceback (most recent call last):
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.8/site-packages/sphinx/application.py", line 268, in __init__
    self.events.emit('config-inited', self.config)
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.8/site-packages/hoverxref/extension.py", line 79, in setup_sphinx_tabs
    listeners = list(app.events.listeners.get('html-page-context').items())
AttributeError: 'list' object has no attribute 'items'

Exception occurred:
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.8/site-packages/hoverxref/extension.py", line 79, in setup_sphinx_tabs
    listeners = list(app.events.listeners.get('html-page-context').items())
AttributeError: 'list' object has no attribute 'items'
```

By the way, thanks for this wonderful extension :sparkles:

**Comment by humitos** [comment]
Thanks for reporting this! I fixed the issue in #46. It will be included in the next release, hopefully next week :)
